accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup_success/', views.signup_success, name='signup_success'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

reading_blog/urls.py
from django.urls import path
from . import views

app_name = 'reading_blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('<int:pk>/comment/new/', views.comment_new, name='comment_new'),
    path('posttag/<str:tag>/', views.posttag, name='posttag'),
]

tutorialdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('reading_blog/', include('reading_blog.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

main/models.py
from django.db import models

reading_blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    content = models.TextField()
    thumb_image = models.ImageField(
        upload_to='reading_blog/images/%Y/%m/%d/', blank=True)
    image_upload = models.ImageField(upload_to='blog/%Y/%m/%d/', blank=True, null=True)
    file_upload = models.FileField(
        upload_to='reading_blog/files/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    view_count = models.PositiveIntegerField(default=0)
    tags = models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return f'/reading_blog/{self.pk}/'
    
class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments'
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE
    )
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.message
    
    
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name

reading_blog/forms.py
from django import forms
from .models import Post, Comment, Tag

class PostForm(forms.ModelForm):
    title = forms.CharField(label="제목", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(label="내용", widget=forms.Textarea(attrs={'class': 'form-control'}))
    image_upload = forms.ImageField(label="이미지 업로드", required=False, widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,)
    
    class Meta:
        model = Post
        fields = ['title', 'content', 'image_upload', 'tags']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']


class TagForm(forms.ModelForm):
    name = forms.ModelChoiceField(
        queryset=Tag.objects.all(),
        empty_label="Select a tag",
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="태그"
    )

    class Meta:
        model = Tag
        fields = ['name']

accounts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render
from django.views.generic import CreateView

def signup_success(request):
    return render(request, 'accounts/signup_success.html')

signup = CreateView.as_view(
    form_class = UserCreationForm,
    template_name = 'accounts/signup.html',
    success_url = '/accounts/signup_success/',
)

login = LoginView.as_view(
    template_name = 'accounts/login.html',
    next_page = '/'
)

logout = LogoutView.as_view(
    next_page = '/'
)

main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html')

reading_blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.views.generic import ListView, DeleteView, UpdateView, DetailView, CreateView
from .models import Post, Comment
from .forms import PostForm, CommentForm, TagForm
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


class PostList(ListView):
    model = Post
    ordering = '-pk'

    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get('q', '')
        if q:
            qs = qs.filter(title__icontains=q)
        return qs

post_list = PostList.as_view()


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('reading_blog:post_list')
    template_name = 'reading_blog/post_write.html'

    def form_valid(self, form):
        video = form.save(commit=False)
        video.author = self.request.user
        return super().form_valid(form)

post_new = PostCreate.as_view()


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context
    
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        post = Post.objects.get(pk=pk)
        post.view_count += 1
        post.save()
        return super().get_object(queryset)

post_detail = PostDetail.as_view()


class PostUpdate(UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('reading_blog:post_list')
    template_name = 'reading_blog/post_write.html'

    def test_func(self):
        return self.get_object().author == self.request.user

post_edit = PostUpdate.as_view()


class PostDelete(UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('reading_blog:post_list')

    def test_func(self):
        return self.get_object().author == self.request.user

post_delete = PostDelete.as_view()


@login_required
def comment_new(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('reading_blog:post_detail', pk)
    else:
        form = CommentForm()
    return render(request, 'reading_blog/post_write.html', {
        'form': form,
    })


def posttag(request, tag):
    posts = Post.objects.filter(tags__name__iexact=tag)
    return render(request, 'reading_blog/post_list.html', {'post_list': posts, 'tag': tag})

templates/accounts/form.html
<h1>회원가입</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="입력">
</form>

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-4">
    <div class="card">
        <div class="card-body text-center">
            <h4>로그인</h4>
            <hr>
            <form style="margin-top: 70px; margin-bottom: 70px;" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="mx-auto">
                    {{ form.as_table }}
                </table>
                <div class="mt-4">
                    <button type="submit" class="btn btn-info">로그인</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-4">
    <div class="card">
        <div class="card-body text-center">
            <h4>회원가입</h4>
            <hr>
            <form style="margin-top: 50px; margin-bottom: 50px;" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="mx-auto">
                    {{ form.as_table }}
                </table>
                <div class="mt-4">
                    <button type="submit" class="btn btn-info">회원가입</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/signup_success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-4 mb-4">
    <div class="card">
        <div class="card-body text-center">
                {% csrf_token %}
                <h4 style="margin-top: 40px; margin-bottom: 60px;">회원가입이 성공적으로 완료되었습니다</h4>
                <div class="d-flex justify-content-center mt-3">
                    <a href="{% url 'accounts:login' %}" class="btn btn-secondary">로그인</a>
                </div>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE-edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>오늘의 책</title>
        <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        <nav class="navbar navbar-expand-lg navbar-light bg-info" style="height: 60px;" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'main:index' %}">TODAY'S BOOK</a>
            </div>
        </nav>
    </head>

    <style>
        body{
            font-family: Arial, sans-serif;
        }
    </style>
    <body>

        {% block content %}
        {% endblock %}

        <footer class="bg-light text-center text-lg-start mt-5">
            <div class="text-center p-3 text-secondary">
                Copyright © 2023 All rights reserved
            </div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-4 text-center">
    <img class="photo" src="../static/asset/main_img.jpg" alt="메인이미지" style="width: 400px; height: auto;">
    <h6 class="text-info">📝오늘 읽은 책의 감상과 후기를 남길 수 있는 블로그 오늘의 책입니다📝</h6>
    <div class="btn-row" style="margin-top: 65px; margin-bottom: 25px;">
        <a href="{% url 'reading_blog:post_list' %}" class="btn btn-info">블로그 입장하기</a>
    </div>
    <div class="btn-row">
        <a href="{% url 'accounts:signup' %}" class="btn btn-secondary">회원가입</a>
        <a href="{% url 'accounts:login' %}" class="btn btn-secondary">로그인</a>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}" class="btn btn-secondary">로그아웃</a>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/reading_blog/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <h4>글 작성</h4>
            <hr>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                    <label for="id_title" class="col-sm-2 col-form-label text-info"><h6>제목</h6></label>
                    <div>
                        {{ form.title }}
                    </div>
                
                
                    <label for="id_content" class="col-sm-2 col-form-label text-info"><h6>내용</h6></label>
                    <div>
                        {{ form.content }}
                    </div>
                    <hr>
        
                    <label for="id_image_upload" class="col-sm-2 col-form-label text-info"><h6>이미지 업로드</h6></label>
                    <div>
                        {{ form.image_upload }}
                    </div>

                    <hr>
                    <label for="id_tags" class="text-info"><h6>태그</h6></label>
                    <div class="form-check form-check-inline">
                        {% for tag in form.tags %}
                        {{ tag }}
                        {% endfor %} </div>
                <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
        <button type="submit" class="btn btn-info" style="float: right;">등록</button>
    </div>
</div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/reading_blog/post_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-4 mb-4">
    <div class="card">
        <div class="card-body text-center">
            <form method="post" class="mt-6 mb-6">
                {% csrf_token %}
                <h4 style="margin-top: 40px; margin-bottom: 60px;">글을 삭제하시겠습니까?</h4>
                <div class="d-flex justify-content-center">
                    <input type="submit" value="네" class="btn btn-info">
                </div>
                <div class="d-flex justify-content-center mt-3">
                    <a href="{% url 'reading_blog:post_list' %}" class="btn btn-secondary">아니요</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/reading_blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{ post.title }}</h4>
            <hr>
            <p class="card-text">
                <small class="text-muted">
                    작성자: {{ post.author.username }} | 작성일: {{ post.created_at|date:"Y.m.d" }} | 조회수: {{ post.view_count }}
                </small>
            </p>
            <p class="card-text" style="font-size: 1.0em;">
                {{ post.content }}
            </p>
        
            {% if post.image_upload %}
                <img src="{{ post.image_upload.url }}" class="img-fluid" alt="Image" style="max-width: 60%; height: auto;">
            {% endif %}
            
            <hr>
            <p class="card-text">
                <small>
                    {% for tag in post.tags.all %}
                        <a href="{% url 'reading_blog:posttag' tag.name %}" style="color: #999;">#{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </small>
            </p>
        </div>
    </div>
    
    <div class="mt-4">
        <h5 class="text-info">댓글</h5>
        <ul class="list-group">
            {% for comment in post.comments.all %}
                <li class="list-group-item"  style="font-size: 0.9em; margin-top: 5px; margin-bottom: 5px;">
                    {{ comment.message }}
                    <br>
                    <small class="text-muted">
                        {{ comment.author }} | {{ comment.created_at|date:"Y.m.d" }}
                    </small>
                </li>
            {% endfor %}
        </ul>

        {% if post.comments.all.count < 1 %}
            <p>댓글이 없습니다.</p>
        {% endif %}
    </div>
    
    <div class="mt-4">
        <form action="{% url 'reading_blog:comment_new' post.pk %}" method="post" style="width: 100%;">
            {% csrf_token %}
            <div class="form-row">
                <div class="col">
                    <textarea name="message" class="form-control" rows="3" placeholder="댓글을 입력하세요" required id="id_message"></textarea>
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-info" style="float: right;">댓글 등록</button>
                </div>
            </div>
        </form>
    </div>

    <div class="text-left mt-4">
        <a href="{% url 'reading_blog:post_list' %}" class="btn btn-secondary">목록</a>
        {% if user == post.author %}
            <a href="{% url 'reading_blog:post_edit' post.pk %}" class="btn btn-secondary">수정</a>
            <a href="{% url 'reading_blog:post_delete' post.pk %}" class="btn btn-secondary">삭제</a>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/reading_blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center">
        <h4>글 목록</h4>
        <form class="form-inline" action="" method="GET">
            <div class="input-group">
                <input class="form-control" type="text" name="q" value="{{ request.GET.q }}" placeholder="내용을 입력하세요.">
                <div class="input-group-append">
                    <button class="btn btn-secondary" type="submit">검색</button>
                </div>
            </div>
        </form>
    </div>

    <table class="table table-bordered mt-4 text-center table-hover text-dark">
        <thead class="table-light">
        {% if post_list %}
        <tr class="table-info">
            <th class="col-5">제목</th>
            <th class="col-3">작성자</th>
            <th class="col-3">작성일</th>
            <th class="col-1">조회수</th>
        </tr>
        </thead>
        <tbody>
        {% for post in post_list %}
        <tr>
            <td class="col-5">
                <a href="{% url 'reading_blog:post_detail' pk=post.pk %}" class="btn">{{ post.title }}</a>
                {% if post.comments.count > 0 %}
                <span class="text-success small ml-2">{{ post.comments.count }}</span>
                {% endif %}
            </td>
            <td class="col-3">{{ post.author.username }}</td>
            <td class="col-3">{{ post.created_at|date:"Y.m.d" }}</td>
            <td class="col-1">{{ post.view_count }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    {% else %}
    <p>작성된 게시글이 없습니다.</p>
    {% endif %}

    <div class="text-left mt-4">
        <a href="{% url 'main:index' %}" class="btn btn-secondary">메인</a>
        <a href="{% url 'reading_blog:post_new' %}" class="btn btn-secondary">글작성</a>
        {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}" class="btn btn-secondary">로그아웃</a>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/reading_blog/post_write.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <h4>글 작성</h4>
            <hr>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                    <label for="id_title" class="col-sm-2 col-form-label text-info"><h6>제목</h6></label>
                    <div>
                        {{ form.title }}
                    </div>
                
                
                    <label for="id_content" class="col-sm-2 col-form-label text-info"><h6>내용</h6></label>
                    <div>
                        {{ form.content }}
                    </div>
                    <hr>
        
                    <label for="id_image_upload" class="col-sm-2 col-form-label text-info"><h6>이미지 업로드</h6></label>
                    <div>
                        {{ form.image_upload }}
                    </div>

                    <hr>
                    <label for="id_tags" class="text-info"><h6>태그</h6></label>
                    <div class="form-check form-check-inline">
                        {% for tag in form.tags %}
                        {{ tag }}
                        {% endfor %} </div>
                <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
        <button type="submit" class="btn btn-info" style="float: right;">등록</button>
    </div>
</div>
            </form>
        </div>
    </div>
</div>
{% endblock %}